// apps/docs-react/src/App.tsx
import { useMemo } from 'react';
import {
  createDashboardStore,
  DashboardActiveFilters,
  SelectionLegend,
  CrossfilteredBarChart,
  SmallMultiples,
  DrillBarChart,
  DrillBreadcrumb,
  RecordsTable,
  TopNFilter,
  ValueSlicer,
  RelativeDateFilter,
  RangeSliderFilter,
  ExportMenu,
} from '@sentropic/dataviz-react';
import { model, data, crossfilter, DEMO_NOW } from './data.js';
import './app.css';

const legendLabels = { byCountry: 'Pays', byProduct: 'Produit' };

export function App() {
  const store = useMemo(() => createDashboardStore({ model, data, crossfilter }), []);
  return (
    <main className="page">
      <header className="page__head">
        <div>
          <h1>dataviz — démo cross-filter (React)</h1>
          <p>
            Tout est piloté par l'état partagé <code>@sentropic/dataviz-core</code> ; la présentation
            vient à 100 % du design system Sent Tech.
          </p>
        </div>
        <ExportMenu store={store} />
      </header>

      <section className="bar">
        <DashboardActiveFilters store={store} />
        <SelectionLegend store={store} labels={legendLabels} />
      </section>

      <section className="controls">
        <ValueSlicer store={store} dimension="country" orientation="horizontal" />
        <TopNFilter store={store} dimension="product" measure="sales" defaultN={2} label="Top N produits" />
        <RelativeDateFilter store={store} dimension="date" now={DEMO_NOW} label="Période" />
        <RangeSliderFilter store={store} dimension="price" step={1} />
      </section>

      <section className="charts">
        <article className="card">
          <h2>Ventes par pays</h2>
          <p className="hint">Clique une barre pour filtrer les autres vues.</p>
          <CrossfilteredBarChart store={store} viewId="byCountry" dimension="country" measure="sales" label="Ventes par pays" />
        </article>
        <article className="card">
          <h2>Ventes par produit</h2>
          <p className="hint">Lié à la sélection « Pays » (et inversement).</p>
          <CrossfilteredBarChart store={store} viewId="byProduct" dimension="product" measure="sales" label="Ventes par produit" tone="category2" />
        </article>
      </section>

      <section className="card">
        <h2>Small multiples — ventes par produit, par pays</h2>
        <SmallMultiples store={store} viewId="facets" facetBy="country" dimension="product" measure="sales" label="Ventes" columns={3} />
      </section>

      <section className="card">
        <h2>Drill — pays → ville</h2>
        <DrillBreadcrumb store={store} viewId="drill" hierarchy={['country', 'city']} />
        <DrillBarChart store={store} viewId="drill" hierarchy={['country', 'city']} measure="sales" label="Ventes (drill)" tone="category3" />
      </section>

      <section className="card">
        <h2>Enregistrements (cross-filtrés)</h2>
        <RecordsTable store={store} pageSize={8} />
      </section>
    </main>
  );
}

// apps/docs-vue/src/App.vue
<script setup lang="ts">
import {
  createDashboardStore,
  DashboardActiveFilters,
  SelectionLegend,
  CrossfilteredBarChart,
  SmallMultiples,
  DrillBarChart,
  DrillBreadcrumb,
  RecordsTable,
  TopNFilter,
  ValueSlicer,
  RelativeDateFilter,
  RangeSliderFilter,
  ExportMenu,
} from '@sentropic/dataviz-vue';
import { model, data, crossfilter, DEMO_NOW } from './data';

const store = createDashboardStore({ model, data, crossfilter });
const legendLabels = { byCountry: 'Pays', byProduct: 'Produit' };
const drillHierarchy = ['country', 'city'];
</script>

<template>
  <main class="page">
    <header class="page__head">
      <div>
        <h1>dataviz — démo cross-filter (Vue)</h1>
        <p>
          Tout est piloté par l'état partagé <code>@sentropic/dataviz-core</code> ; la présentation
          vient à 100 % du design system Sent Tech.
        </p>
      </div>
      <ExportMenu :store="store" />
    </header>

    <section class="bar">
      <DashboardActiveFilters :store="store" />
      <SelectionLegend :store="store" :labels="legendLabels" />
    </section>

    <section class="controls">
      <ValueSlicer :store="store" dimension="country" orientation="horizontal" />
      <TopNFilter :store="store" dimension="product" measure="sales" :default-n="2" label="Top N produits" />
      <RelativeDateFilter :store="store" dimension="date" :now="DEMO_NOW" label="Période" />
      <RangeSliderFilter :store="store" dimension="price" :step="1" />
    </section>

    <section class="charts">
      <article class="card">
        <h2>Ventes par pays</h2>
        <p class="hint">Clique une barre pour filtrer les autres vues.</p>
        <CrossfilteredBarChart :store="store" view-id="byCountry" dimension="country" measure="sales" label="Ventes par pays" />
      </article>
      <article class="card">
        <h2>Ventes par produit</h2>
        <p class="hint">Lié à la sélection « Pays » (et inversement).</p>
        <CrossfilteredBarChart :store="store" view-id="byProduct" dimension="product" measure="sales" label="Ventes par produit" tone="category2" />
      </article>
    </section>

    <section class="card">
      <h2>Small multiples — ventes par produit, par pays</h2>
      <SmallMultiples :store="store" view-id="facets" facet-by="country" dimension="product" measure="sales" label="Ventes" :columns="3" />
    </section>

    <section class="card">
      <h2>Drill — pays → ville</h2>
      <DrillBreadcrumb :store="store" view-id="drill" :hierarchy="drillHierarchy" />
      <DrillBarChart :store="store" view-id="drill" :hierarchy="drillHierarchy" measure="sales" label="Ventes (drill)" tone="category3" />
    </section>

    <section class="card">
      <h2>Enregistrements (cross-filtrés)</h2>
      <RecordsTable :store="store" :page-size="8" />
    </section>
  </main>
</template>
