// packages/dataviz-svelte/src/lib/DashboardFilterBar.svelte
<script lang="ts" module>
  import type { DashboardStore } from '@sentropic/dataviz-core';

  export type DashboardFilterBarProps = {
    /** The dashboard store to bind to. */
    store: DashboardStore;
    /** Aria-label of the filter group. */
    label?: string;
    /** Label of the "clear all" button (design-system default otherwise). */
    clearAllLabel?: string;
    class?: string;
  };
</script>

<script lang="ts">
  import { FilterBar, FilterPill } from '@sentropic/design-system-svelte';
  import { findDimension, describeFilterSpec } from '@sentropic/dataviz-core';
  import { useDashboard } from '../adapter.js';

  let {
    store,
    label = 'Filtres actifs',
    clearAllLabel,
    class: className,
  }: DashboardFilterBarProps = $props();

  // `store` is read inside `$derived` (a reactive context) so the readable is
  // re-created if the prop changes; `$dash` auto-subscribes (SSR-safe).
  const dash = $derived(useDashboard(store));
  const entries = $derived(Object.entries($dash.filters));
</script>

<FilterBar
  {label}
  {clearAllLabel}
  class={className}
  onClearAll={entries.length > 0
    ? () => {
        for (const id of Object.keys($dash.filters)) store.clearFilter(id);
      }
    : undefined}
>
  {#each entries as [dimensionId, spec] (dimensionId)}
    {@const dimension = findDimension(store.model, dimensionId)}
    <FilterPill
      field={dimension?.label ?? dimensionId}
      value={describeFilterSpec(spec, dimension)}
      onRemove={() => store.clearFilter(dimensionId)}
    />
  {/each}
</FilterBar>

// packages/dataviz-react/src/lib/DashboardFilterBar.tsx
import { FilterBar, FilterPill } from '@sentropic/design-system-react';
import { describeFilterSpec, findDimension, type DashboardStore } from '@sentropic/dataviz-core';
import { useDashboard } from '../adapter.js';

export type DashboardFilterBarProps = {
  /** The dashboard store to bind to. */
  store: DashboardStore;
  /** Aria-label of the filter group. */
  label?: string;
  /** Label of the "clear all" button (design-system default otherwise). */
  clearAllLabel?: string;
  className?: string;
};

/**
 * Active filters rendered as design-system `FilterPill`s wired to the store.
 * "Clear all" clears only the filters, leaving any selections intact.
 */
export function DashboardFilterBar({
  store,
  label = 'Filtres actifs',
  clearAllLabel,
  className,
}: DashboardFilterBarProps) {
  const state = useDashboard(store);
  const entries = Object.entries(state.filters);
  return (
    <FilterBar
      label={label}
      clearAllLabel={clearAllLabel}
      className={className}
      onClearAll={
        entries.length > 0
          ? () => {
              for (const id of Object.keys(store.getState().filters)) store.clearFilter(id);
            }
          : undefined
      }
    >
      {entries.map(([dimensionId, spec]) => {
        const dimension = findDimension(store.model, dimensionId);
        return (
          <FilterPill
            key={dimensionId}
            field={dimension?.label ?? dimensionId}
            value={describeFilterSpec(spec, dimension)}
            onRemove={() => store.clearFilter(dimensionId)}
          />
        );
      })}
    </FilterBar>
  );
}
