// packages/dataviz-svelte/src/lib/DonutChart.svelte
<script lang="ts" module>
  import type { DashboardStore, PartWholeSort } from '@sentropic/dataviz-core';

  export type DonutChartProps = {
    store: DashboardStore;
    viewId: string;
    category: string;
    measure: string;
    sort?: PartWholeSort;
    size?: number;
    thickness?: number;
    centerLabel?: string | null;
    label: string;
    class?: string;
  };
</script>

<script lang="ts">
  import { DonutChart as DsDonutChart, type DonutChartDatum } from '@sentropic/design-system-svelte';
  import { useDashboard } from '../adapter.js';
  import { buildSafePartWholeModel, toPartWholeData } from './partOfWholeData.js';

  let {
    store,
    viewId,
    category,
    measure,
    sort = 'input',
    size,
    thickness,
    centerLabel,
    label,
    class: className,
  }: DonutChartProps = $props();

  const dash = $derived(useDashboard(store));
  const data = $derived.by((): DonutChartDatum[] => {
    void $dash;
    const model = buildSafePartWholeModel(store.model, store.applyCrossfilter(viewId), { category, measure, sort });
    return toPartWholeData(model.items);
  });
</script>

<DsDonutChart {data} {label} {size} {thickness} {centerLabel} class={className} />

// packages/dataviz-react/src/lib/DonutChart.tsx
import {
  DonutChart as DsDonutChart,
  type DonutChartDatum,
} from '@sentropic/design-system-react';
import type { DashboardStore, PartWholeSort } from '@sentropic/dataviz-core';
import { useDashboard } from '../adapter.js';
import { buildSafePartWholeModel, toPartWholeData } from './partOfWholeData.js';

export type DonutChartProps = {
  store: DashboardStore;
  viewId: string;
  category: string;
  measure: string;
  sort?: PartWholeSort;
  size?: number;
  thickness?: number;
  centerLabel?: string | null;
  label: string;
  className?: string;
};

export function DonutChart({
  store,
  viewId,
  category,
  measure,
  sort = 'input',
  size,
  thickness,
  centerLabel,
  label,
  className,
}: DonutChartProps) {
  const state = useDashboard(store);
  void state;

  const model = buildSafePartWholeModel(store.model, store.applyCrossfilter(viewId), { category, measure, sort });
  const data: DonutChartDatum[] = toPartWholeData(model.items);

  return (
    <DsDonutChart
      data={data}
      label={label}
      size={size}
      thickness={thickness}
      centerLabel={centerLabel}
      className={className}
    />
  );
}
