// packages/dataviz-svelte/src/lib/FieldPane.svelte
<script lang="ts" module>
  import type { DataModel, FieldId } from '@sentropic/dataviz-core';

  export type FieldPaneProps = {
    model: DataModel;
    includeDimensions?: boolean;
    includeMeasures?: boolean;
    selectedId?: FieldId | string;
    defaultExpandedIds?: string[];
    label?: string;
    class?: string;
  };
</script>

<script lang="ts">
  import { TreeView } from '@sentropic/design-system-svelte';
  import { buildFieldPaneTree } from '@sentropic/dataviz-core';

  let {
    model,
    includeDimensions,
    includeMeasures,
    selectedId,
    defaultExpandedIds,
    label = 'Fields',
    class: className,
  }: FieldPaneProps = $props();

  const tree = $derived(buildFieldPaneTree(model, { includeDimensions, includeMeasures }));
</script>

<TreeView
  nodes={tree.nodes}
  selected={selectedId}
  defaultExpanded={defaultExpandedIds ?? tree.defaultExpandedIds}
  {label}
  class={className}
/>

// packages/dataviz-react/src/lib/FieldPane.tsx
import {
  TreeView,
  type TreeViewProps,
} from '@sentropic/design-system-react';
import {
  buildFieldPaneTree,
  type DataModel,
  type FieldId,
} from '@sentropic/dataviz-core';

export type FieldPaneProps = Omit<
  TreeViewProps,
  'nodes' | 'selectedId' | 'expandedIds' | 'defaultExpandedIds'
> & {
  model: DataModel;
  includeDimensions?: boolean;
  includeMeasures?: boolean;
  selectedId?: FieldId | string;
  expandedIds?: TreeViewProps['expandedIds'];
  defaultExpandedIds?: TreeViewProps['defaultExpandedIds'];
  label?: string;
};

export function FieldPane({
  model,
  includeDimensions,
  includeMeasures,
  selectedId,
  expandedIds,
  defaultExpandedIds,
  label = 'Fields',
  ...rest
}: FieldPaneProps) {
  const tree = buildFieldPaneTree(model, { includeDimensions, includeMeasures });

  return (
    <TreeView
      {...rest}
      nodes={tree.nodes}
      selectedId={selectedId}
      expandedIds={expandedIds}
      defaultExpandedIds={defaultExpandedIds ?? tree.defaultExpandedIds}
      aria-label={rest['aria-label'] ?? label}
    />
  );
}
