// packages/dataviz-svelte/src/lib/GeoFlowMap.svelte
<script lang="ts" module>
  import type { DashboardStore } from '@sentropic/dataviz-core';

  export type GeoFlowMapProps = {
    store: DashboardStore;
    viewId: string;
    sourceLatitude: string;
    sourceLongitude: string;
    targetLatitude: string;
    targetLongitude: string;
    value?: string;
    width?: number;
    height?: number;
    label: string;
    class?: string;
  };
</script>

<script lang="ts">
  import { GeoMap as DsGeoMap } from '@sentropic/design-system-svelte';
  import { useDashboard } from '../adapter.js';
  import { flowLayer, mapClass } from './geoMapLayers.js';

  let {
    store,
    viewId,
    sourceLatitude,
    sourceLongitude,
    targetLatitude,
    targetLongitude,
    value,
    width = 520,
    height = 320,
    label,
    class: className,
  }: GeoFlowMapProps = $props();

  const dash = $derived(useDashboard(store));
  const layer = $derived.by(() => {
    void $dash;
    return flowLayer(store, viewId, {
      sourceLatitude,
      sourceLongitude,
      targetLatitude,
      targetLongitude,
      value,
      labelText: label,
    });
  });
  const layers = $derived([layer]);
  const classes = $derived(mapClass('st-geoFlowMap', className));
</script>

<DsGeoMap {layers} {width} {height} {label} class={classes} />

// packages/dataviz-react/src/lib/GeoFlowMap.tsx
import type { DashboardStore } from '@sentropic/dataviz-core';
import { GeoMap } from '@sentropic/design-system-react';
import { useDashboard } from '../adapter.js';
import { flowLayer, mapClass } from './geoMapLayers.js';

export type GeoFlowMapProps = {
  store: DashboardStore;
  viewId: string;
  sourceLatitude: string;
  sourceLongitude: string;
  targetLatitude: string;
  targetLongitude: string;
  value?: string;
  width?: number;
  height?: number;
  label: string;
  className?: string;
};

export function GeoFlowMap({
  store,
  viewId,
  sourceLatitude,
  sourceLongitude,
  targetLatitude,
  targetLongitude,
  value,
  width = 520,
  height = 320,
  label,
  className,
}: GeoFlowMapProps) {
  const state = useDashboard(store);
  void state;
  const layer = flowLayer(store, viewId, {
    sourceLatitude,
    sourceLongitude,
    targetLatitude,
    targetLongitude,
    value,
    labelText: label,
  });

  return (
    <GeoMap
      layers={[layer]}
      width={width}
      height={height}
      label={label}
      className={mapClass('st-geoFlowMap', className)}
    />
  );
}
