// packages/dataviz-svelte/src/lib/GeoHexbinMap.svelte
<script lang="ts" module>
  import type { DashboardStore } from '@sentropic/dataviz-core';

  export type GeoHexbinMapProps = {
    store: DashboardStore;
    viewId: string;
    latitude: string;
    longitude: string;
    value?: string;
    cellSize?: number;
    width?: number;
    height?: number;
    label: string;
    class?: string;
  };
</script>

<script lang="ts">
  import { buildGeoHexbinModel } from '@sentropic/dataviz-core';
  import { useDashboard } from '../adapter.js';
  import { GEO_TONES, hexagonPoints, projectCoordinate, scaleNumber } from './geoMapLayout.js';

  let {
    store,
    viewId,
    latitude,
    longitude,
    value,
    cellSize,
    width = 520,
    height = 320,
    label,
    class: className,
  }: GeoHexbinMapProps = $props();

  const dash = $derived(useDashboard(store));
  const model = $derived.by(() => {
    void $dash;
    return buildGeoHexbinModel(store.model, store.applyCrossfilter(viewId), { latitude, longitude, value, cellSize });
  });
  const bins = $derived.by(() => {
    const max = Math.max(1, ...model.bins.map((bin) => bin.value));
    return model.bins.map((bin, index) => {
      const point = projectCoordinate(bin.center, width, height);
      return {
        bin,
        points: hexagonPoints(point.x, point.y, scaleNumber(bin.value, 0, max, 10, 22)),
        fill: GEO_TONES[index % GEO_TONES.length],
      };
    });
  });
</script>

<svg
  role="img"
  aria-label={label}
  class={['st-geoHexbinMap', className].filter(Boolean).join(' ')}
  {width}
  {height}
  viewBox="0 0 {width} {height}"
>
  <title>{label}</title>
  {#each bins as item (item.bin.id)}
    <polygon class="st-geoHexbinMap__bin" points={item.points} fill={item.fill} fill-opacity="0.72">
      <title>{item.bin.id}: {item.bin.value}</title>
    </polygon>
  {/each}
</svg>

// packages/dataviz-react/src/lib/GeoHexbinMap.tsx
import { buildGeoHexbinModel, type DashboardStore } from '@sentropic/dataviz-core';
import { useDashboard } from '../adapter.js';
import { GEO_TONES, hexagonPoints, projectCoordinate, scaleNumber } from './geoMapLayout.js';

export type GeoHexbinMapProps = {
  store: DashboardStore;
  viewId: string;
  latitude: string;
  longitude: string;
  value?: string;
  cellSize?: number;
  width?: number;
  height?: number;
  label: string;
  className?: string;
};

export function GeoHexbinMap({
  store,
  viewId,
  latitude,
  longitude,
  value,
  cellSize,
  width = 520,
  height = 320,
  label,
  className,
}: GeoHexbinMapProps) {
  const state = useDashboard(store);
  void state;
  const model = buildGeoHexbinModel(store.model, store.applyCrossfilter(viewId), { latitude, longitude, value, cellSize });
  const max = Math.max(1, ...model.bins.map((bin) => bin.value));

  return (
    <svg
      role="img"
      aria-label={label}
      className={['st-geoHexbinMap', className].filter(Boolean).join(' ') || undefined}
      width={width}
      height={height}
      viewBox={`0 0 ${width} ${height}`}
    >
      <title>{label}</title>
      {model.bins.map((bin, index) => {
        const point = projectCoordinate(bin.center, width, height);
        const radius = scaleNumber(bin.value, 0, max, 10, 22);
        return (
          <polygon
            key={bin.id}
            className="st-geoHexbinMap__bin"
            points={hexagonPoints(point.x, point.y, radius)}
            fill={GEO_TONES[index % GEO_TONES.length]}
            fillOpacity="0.72"
          >
            <title>{`${bin.id}: ${bin.value}`}</title>
          </polygon>
        );
      })}
    </svg>
  );
}
