// packages/dataviz-svelte/src/lib/GeoJsonMap.svelte
<script lang="ts" module>
  import type { DashboardStore } from '@sentropic/dataviz-core';

  export type GeoJsonMapProps = {
    store: DashboardStore;
    viewId: string;
    geometry: string;
    id?: string;
    labelField?: string;
    value?: string;
    width?: number;
    height?: number;
    label: string;
    class?: string;
  };
</script>

<script lang="ts">
  import { GeoMap as DsGeoMap } from '@sentropic/design-system-svelte';
  import { useDashboard } from '../adapter.js';
  import { geojsonLayer, mapClass } from './geoMapLayers.js';

  let {
    store,
    viewId,
    geometry,
    id,
    labelField,
    value,
    width = 520,
    height = 320,
    label,
    class: className,
  }: GeoJsonMapProps = $props();

  const dash = $derived(useDashboard(store));
  const layer = $derived.by(() => {
    void $dash;
    return geojsonLayer(store, viewId, {
      geometry,
      id,
      label: labelField,
      value,
      labelText: label,
    });
  });
  const layers = $derived([layer]);
  const classes = $derived(mapClass('st-geoJsonMap', className));
</script>

<DsGeoMap {layers} {width} {height} {label} class={classes} />

// packages/dataviz-react/src/lib/GeoJsonMap.tsx
import type { DashboardStore } from '@sentropic/dataviz-core';
import { GeoMap } from '@sentropic/design-system-react';
import { useDashboard } from '../adapter.js';
import { geojsonLayer, mapClass } from './geoMapLayers.js';

export type GeoJsonMapProps = {
  store: DashboardStore;
  viewId: string;
  geometry: string;
  id?: string;
  labelField?: string;
  value?: string;
  width?: number;
  height?: number;
  label: string;
  className?: string;
};

export function GeoJsonMap({
  store,
  viewId,
  geometry,
  id,
  labelField,
  value,
  width = 520,
  height = 320,
  label,
  className,
}: GeoJsonMapProps) {
  const state = useDashboard(store);
  void state;
  const layer = geojsonLayer(store, viewId, {
    geometry,
    id,
    label: labelField,
    value,
    labelText: label,
  });

  return (
    <GeoMap
      layers={[layer]}
      width={width}
      height={height}
      label={label}
      className={mapClass('st-geoJsonMap', className)}
    />
  );
}
